//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;



/// <summary>
///   一个强类型的资源类，用于查找本地化的字符串等。
/// </summary>
// 此类是由 StronglyTypedResourceBuilder
// 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
// 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
// (以 /str 作为命令选项)，或重新生成 VS 项目。
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class HMIEditEnvironment_图标 {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal HMIEditEnvironment_图标() {
    }
    
    /// <summary>
    ///   返回此类使用的缓存的 ResourceManager 实例。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HMIEditEnvironment.图标", typeof(HMIEditEnvironment_图标).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   重写当前线程的 CurrentUICulture 属性，对
    ///   使用此强类型资源类的所有资源查找执行重写。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   查找 System.Drawing.Bitmap 类型的本地化资源。
    /// </summary>
    internal static System.Drawing.Bitmap bezier_small {
        get {
            object obj = ResourceManager.GetObject("bezier_small", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   查找 System.Drawing.Bitmap 类型的本地化资源。
    /// </summary>
    internal static System.Drawing.Bitmap circleRect_small {
        get {
            object obj = ResourceManager.GetObject("circleRect_small", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   查找 System.Drawing.Bitmap 类型的本地化资源。
    /// </summary>
    internal static System.Drawing.Bitmap ell_small {
        get {
            object obj = ResourceManager.GetObject("ell_small", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   查找 System.Drawing.Bitmap 类型的本地化资源。
    /// </summary>
    internal static System.Drawing.Bitmap FillLeft {
        get {
            object obj = ResourceManager.GetObject("FillLeft", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   查找 System.Drawing.Bitmap 类型的本地化资源。
    /// </summary>
    internal static System.Drawing.Bitmap FillRight {
        get {
            object obj = ResourceManager.GetObject("FillRight", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   查找 System.Drawing.Bitmap 类型的本地化资源。
    /// </summary>
    internal static System.Drawing.Bitmap line_small {
        get {
            object obj = ResourceManager.GetObject("line_small", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   查找 System.Drawing.Bitmap 类型的本地化资源。
    /// </summary>
    internal static System.Drawing.Bitmap polygon_small {
        get {
            object obj = ResourceManager.GetObject("polygon_small", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   查找 System.Drawing.Bitmap 类型的本地化资源。
    /// </summary>
    internal static System.Drawing.Bitmap polyline_small {
        get {
            object obj = ResourceManager.GetObject("polyline_small", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   查找 System.Drawing.Bitmap 类型的本地化资源。
    /// </summary>
    internal static System.Drawing.Bitmap rect_small {
        get {
            object obj = ResourceManager.GetObject("rect_small", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   查找 System.Drawing.Bitmap 类型的本地化资源。
    /// </summary>
    internal static System.Drawing.Bitmap san_small {
        get {
            object obj = ResourceManager.GetObject("san_small", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
    
    /// <summary>
    ///   查找 System.Drawing.Bitmap 类型的本地化资源。
    /// </summary>
    internal static System.Drawing.Bitmap str_small {
        get {
            object obj = ResourceManager.GetObject("str_small", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
        }
    }
}
